apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-test-deployment
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello-test
          image: rawebregistry.azurecr.io/hello:v1.0
          env:
            - name: TEST_URL
              valueFrom:
                secretKeyRef:
                 name: mysecret
                 key: test_url
          ports:
            - containerPort: 9999
      
---

kind: Service
apiVersion: v1
metadata:
  name: hello-test-service
spec:
  loadBalancerIP: 104.42.168.187
  type: LoadBalancer
  #type: NodePort 
  selector:
    app: hello
  ports:
  - port: 9999
    #nodePort: 30003		
