apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-test-deployment
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello-test
          image: rawebregistry.azurecr.io/hello:v1.0
          env:
            - name: TEST_URL
              valueFrom:
                secretKeyRef:
                 name: mysecret
                 key: test_url
          ports:
            - containerPort: 9999
      
---

kind: Service
apiVersion: v1
metadata:
  name: hello-test-service
  #annotations:
  #  service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  #loadBalancerIP: 104.42.168.187
  type: LoadBalancer
  #type: NodePort 
  selector:
    app: hello
  ports:
  - port: 9999
    #nodePort: 30003		

---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  test_url: aHR0cDovL3Rlc3RfdXJsLmNu
  
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-test-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    #kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: hello-test.e6168713fef64be3964a.westus.aksapp.io
    http:
      paths:
      - backend:
          serviceName: hello-test-service
          servicePort: 9999
        path: /  
