apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-test-deployment
  labels:
    app: hello
spec:
  replicas: 6
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello-test
          image: 192.168.15.120:5000/hello_images:v${BUILD_NUMBER}
          env:
            - name: TEST_URL
              valueFrom:
                secretKeyRef:
                 name: mysecret
                 key: test_url
          ports:
            - containerPort: 9999
        
      imagePullSecrets:
        #- name: myregistrykey
        - name: $KUBERNETES_SECRET_NAME
---

kind: Service
apiVersion: v1
metadata:
  name: hello-test-service
spec:
  #type: LoadBalancer
  #type: NodePort 
  selector:
    app: hello
  ports:
  - port: 9999
    #nodePort: 30003		
    
---

apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  test_url: aHR0cDovL3Rlc3RfdXJsLmNu
